/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <android/log.h>

/* Header for class com_yjt_patchbsdiff_BsdiffUtils */

#ifndef _Included_com_yjt_patchbsdiff_BsdiffUtils
#define _Included_com_yjt_patchbsdiff_BsdiffUtils
#ifdef __cplusplus
extern "C" {
#endif

#define LOGD(fmt,...) __android_log_print(3, "C: ", fmt, __VA_ARGS__)

JNIEXPORT void JNICALL Java_com_yjt_patchbsdiff_BsdiffUtils_startPatch
        (JNIEnv *, jclass, jstring, jstring, jstring);


JNIEXPORT void JNICALL Java_com_yjt_patchbsdiff_BsdiffUtils_startCombine
        (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
